### PR TITLE
feat: (misc) handle watching status based on number of server

### PR DESCRIPTION
**Pull request by budimanjojo**
This will make the bot status to "Watching 1 server" or "Watching 100 servers" based on number of servers it's watching.
PS: the code autoformat on save of `gofumpt` is terrible and I don't know how to make it not doing this so apologize beforehand.

### CODE REVIEW

**Comment by tyzbit** [comment]
The functionality is sound but yeah `gufumpt` is mangling the code, see if you can get it to not do that. I don't know how it's being invoked on your machine but in VSCode there's the option to `Save without Formatting`.

**Comment by budimanjojo** [comment]
Yeah I use neovim and me turning on autoformat on save is something I do recently (2-3 months ago). I just found out that I can do `:noautocmd w` to not do autoformat. 🚀

**Comment by budimanjojo** [comment]
I'll fix this commit tomorrow without the autoformatting nonsense because I'm not on PC now.

**Comment by budimanjojo** [comment]
Rebased and fixed the auto formatting bullshit :D

**Comment by tyzbit** [comment]
Beautiful

**Pull request merged**
